# Generated by Django 2.1.7 on 2019-03-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190311_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_desc',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_link',
            field=models.CharField(max_length=500),
        ),
    ]
