# Generated by Django 2.1.7 on 2019-03-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190312_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='youtube',
            field=models.TextField(default='', max_length=100),
        ),
    ]
